version: '3.8'

services:
  frontend:
    build: ./frontend
    image: frontend
    environment:
      - PORT=8080
      - BACKEND_URL=https://fghnrz4uxi.execute-api.eu-west-1.amazonaws.com/dev
    ports:
      - '8080:8080'
