version: '3.8'

services:
  frontend:
    build: ./frontend
    image: frontend
    environment:
      - PORT=8080
      - BACKEND_NAME=localhost
      - BACKEND_PORT=4000
    ports:
      - '8080:8080'
    depends_on:
      - backend
  backend:
    build: ./backend
    image: backend
    environment:
      - PORT=4000
      - MONGODB_NAME=mongodb
      - MONGODB_DATABASE=posts
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_PORT=27017
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    networks:
      - data-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=posts
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - dbdata:/data/db
    networks:
      - data-network

volumes:
  dbdata:

networks:
  data-network:
    driver: bridge
